spring:
  application:
    name: simpleproto
  profiles:
    active: dev
  # Postgres数据源
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://120.27.150.100:5432/${spring.application.name}?currentSchema=${spring.profiles.active}&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: postgres
    password: Wanfeng730
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: create
  jackson:
    # 全局json日期格式
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true
  # mapper xml文件扫描路径
  mapper-locations: classpath:mapper/postgres/*Mapper.xml


cn:
  wanfeng:
    sp:
      tableName: sp_object_table


# 日志配置
logging:
  level:
    root: INFO
    cn.wanfeng.sp.base.SpBaseObjectTest: DEBUG
  file:
    path: ./logs