simpleproto:
  # PostgreSQL配置
  postgresHost: localhost
  postgresPort: 15432
  # ElasticSearch配置
  #   8.x版本根据官方文档部署的需要使用https
  esUris: https://localhost:9200
  esUsername: elastic
  esPassword: UxBe-Hk5=21GLpQg=8Pw
  # 业务数据表名
  dataTable: sp_object_table
  # 业务设置表名
  settingsTable: sp_settings

######################################################
spring:
  application:
    name: simpleproto
  profiles:
    active: dev
  # Postgres数据源
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${simpleproto.postgresHost}:${simpleproto.postgresPort}/${spring.application.name}?currentSchema=${spring.profiles.active}&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: postgres
    password: Wanfeng730
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: create
  jackson:
    # 全局json日期格式
    date-format: yyyy-MM-dd HH:mm:ss
  # ElasticSearch数据源
  elasticsearch:
    uris: ${simpleproto.esUris}
    username: ${simpleproto.esUsername}
    password: ${simpleproto.esPassword}

mybatis-plus:
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true
    interceptor:
      - cn.wanfeng.sp.interceptor.MybatisPlusTableNameInterceptor
  # mapper xml文件扫描路径
  mapper-locations: classpath:mapper/postgres/*Mapper.xml

# 日志配置
logging:
  level:
    root: INFO
    cn.wanfeng.sp.base.SpBaseObjectTest: DEBUG
  file:
    path: ./logs
