# 修改此配置后，需同步更新SimpleProtoConfig的初始化方法
simpleproto:
  # 数据库连接配置(PostgreSQL）
  dataSourceDriver: org.postgresql.Driver
  dataSourceUrl: jdbc:postgresql://42.192.108.249:5432/${spring.application.name}?currentSchema=${spring.profiles.active}&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
  dataSourceUsername: postgres
  dataSourcePassword: Wanfeng730
  # 数据库名称取spring应用名称
  currentScheme: ${spring.profiles.active}
  # OpenSearch 连接配置
  opensearchHostScheme: http
  opensearchHost: 42.192.108.249
  opensearchPort: 9200
  opensearchUsername: admin
  opensearchPassword: Wanfeng730
  # OpenSearch jdbc配置
  opensearchJdbcDriver: com.amazon.opendistroforelasticsearch.jdbc.Driver
  opensearchJdbcUrl: jdbc:elasticsearch://http://42.192.108.249:9200
  opensearchJdbcUseSSL: false
  # 业务数据表名
  dataTable: sp_object_table
  # 业务设置表名
  settingsTable: sp_settings
  # Redis连接配置
  redisHost: 42.192.108.249
  redisPort: 6379
  redisPassword: Wanfeng730
  redisDatabase: 0
  # 文件对象存储连接配置
  fileStorageType: MinIO
  fileStorageEndPoint: http://42.192.108.249:9000
  fileStorageAccessKey: minio
  fileStorageSecretKey: Wanfeng730
  fileStorageBucket: simpleproto
  # Swagger UI配置
  # swaggerScanPackages扫描包路径，多个路径用","分隔（SimpleProto提供一些默认接口，扫描包名为cn.wanfeng.sp.api.controller）
  swaggerScanPackages: cn.wanfeng.sp.web.controller
  swaggerTitle: SimpleProto-API 接口文档
  swaggerAuthor: 晚风
  swaggerAuthorUrl: 晚风的URL
  swaggerAuthorEmail: 2580330397@qq.com
  swaggerDescription: SimpleProto-API 接口文档
  swaggerVersion: 1.1


spStock:
  apiSource: tsanghi
  apiToken: 284bff0a447f408d869468aca8f86338

######################################################
server:
  servlet:
    context-path: /simpleproto
  port: 7300


spring:
  application:
    name: simpleproto
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # Postgres数据源
  datasource:
    postgres:
      driver-class-name: ${simpleproto.dataSourceDriver}
      url: ${simpleproto.dataSourceUrl}
      username: ${simpleproto.dataSourceUsername}
      password: ${simpleproto.dataSourcePassword}
    search:
      driver-class-name: ${simpleproto.opensearchJdbcDriver}
      url: ${simpleproto.opensearchJdbcUrl}
      username: ${simpleproto.opensearchUsername}
      password: ${simpleproto.opensearchPassword}
      useSSL: ${simpleproto.opensearchJdbcUseSSL}
  data:
    redis:
      host: ${simpleproto.redisHost}
      port: ${simpleproto.redisPort}
      password: ${simpleproto.redisPassword}
      database: ${simpleproto.redisDatabase}
  # 数据库连接方言配置
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: create
  # 全局json日期格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  # ElasticSearch数据源
  elasticsearch:
    uris: ${simpleproto.esUris}
    username: ${simpleproto.esUsername}
    password: ${simpleproto.esPassword}
  # message国际化资源文件配置 src/main/resources/i18n/messages.properties
  messages:
    basename: i18n/messages


hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect

mybatis-plus:
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true
  # mapper xml文件扫描路径
  mapper-locations: classpath:mapper/postgres/*Mapper.xml

# 日志配置
logging:
  file:
    path: ./logs
  level:
    root: info
    org.springframework: error
    com.alibaba.nacos: error
    org.apache.dubbo: error
    org.apache.coyote: error
    # 开启sql查询语句debug打印，打印指定包下的mybatis sql
    cn.wanfeng.sp.base.mapper.search: debug
    cn.wanfeng.sp.api.mapper.search.SpFileMapper: debug
    cn.wanfeng.sp.interceptor.MybatisPlusCustomInnerInterceptor: debug

